apiVersion: 1

datasources:
  - name: Prometheus1
    type: prometheus
    url: http://192.168.152.142:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://192.168.152.142:3100
