# ici nous définissons l'ensemble de nos serveurs node exporters

- targets:
    # cette cible désigne le serveur qui héberge aussi prometheus 
    - '192.168.152.142:9100'
  labels:
    instance: 'server-01'
    environment: 'production'

# On pourra dupliquer la ligne précédente plusieurs fois en fonction 

- targets:
    # cette cible désigne un serveur distant sur lequel nous avons déployer node exporter afin de le monitorer depuis notre serveur prometheus
    # il enverra donc ces métriques vers notre serveur prometheus
    - '192.168.152.140:9100'
  labels:
    instance: 'server-02'
    environment: 'production'

