route:
  receiver: admin

receivers:
  - name: admin
    email_configs:
      - to : "wilfriedaudrey.baleba@gmail.com"
        from: "audrey.baleba@facsciences-uy1.cm"
        smarthost: smtp.gmail.com:587
        auth_username: "audrey.baleba@facsciences-uy1.cm"
        auth_identity: "audrey.baleba@facsciences-uy1.cm"
        auth_password: "tzzezivaaayrshwb"
