groups:
  # le mot clé record c'est pour des règles d'enregistrement/stockage
  - name: calcul_cpu
    # Calcul de l'utilisation du processeur
    rules:
    - record: job:idle_cpu_seconds:avg_per_minute
      expr: avg without(cpu)(rate (node_cpu_seconds_total{mode="idle"}[1m]))

    - record: job:non_idle_cpu_seconds:avg_per_minute
      expr: avg without(cpu, mode)(rate (node_cpu_seconds_total{mode!="idle"}[1m]))


  - name: calcul_memoire
    # Calcul de l'utilisation de la mémoire 
    rules:
    - record: job:idle_memory_seconds
      expr: (node_memory_MemFree_bytes/node_memory_MemTotal_bytes)*100

    - record: job:non_idle_memory_seconds
      expr: (1-(node_memory_MemFree_bytes/node_memory_MemTotal_bytes))*100

  # le mot clé alert c'est pour des règles d'alerte 
  - name: node_alert
    # Déclenchement d'une alerte si, le job de node-exporter est down
    rules:
    - alert: node_exporter_status
      expr: up{job="node_exporter"} == 0
      for: 2m

    - record: job:myapp_resposponse_latency_seconds:rate_1m
      expr: rate(myapp_response_latency_seconds_sum{path=~"/user/.+"}[1m]) / rate(myapp_response_latency_seconds_count{path=~"/user/.+"}[1m])

    - alert: Latence_de_l'application_supérieure_5
      expr: job:myapp_resposponse_latency_seconds:rate_1m  >= 5
      for: 2m
      labels:
        sevirity: CRITICAL

    - alert: Latence_de_application_entre_2&5
      expr: 2 < job:myapp_resposponse_latency_seconds:rate_1m  < 5
      for: 2m
      labels:
        sevirity: Warning
      annotations:
        summary: "L'application ne fonctionne pas correctement et les API présentent une latence de 2 à 5 secondes."
        description: "Bonjour l'équipe, la sévérité de cette alerte est de {{ $labels.sevirity }}, une alerte a été déclenchée pour l'instance {{ $labels.instance }}."
